### ISSUE TITLE
Multicluster: Grant remote modules with access to dataset credentials 

### ISSUE THREAD

**Issue by roee88** [mesh-for-data/mesh-for-data#140]
|   |   |
| - | - |
| Design doc | https://docs.google.com/document/d/1zcEMm-geg6QrSrIYuJxgFCDVdXiGNQVB65Llv3i_02s/edit#heading=h.img5h5xmx8ok |
| Parent issue | #134 |
| Required issues | # |

# Description

M4DApplication controller obtains dataset credentials via connectors or configurations. These credentials should then be distributed to modules that need to be granted with access to the data (e.g., an implicit copy job needs credentials to access the source target data stores). Those modules may run in remote clusters.

Please comment in the design doc until we finalize a design and then a PR will be linked to this issue for implementing it. 

Sub issues:
- [ ]  #337  Show the ability of modules to send request to Vault
- [x] #406 Retrieve dataset credentials using Vault plugin
- [ ] #585 Run Vault in non "dev" mode
