### ISSUE TITLE
Show the ability of modules to send request to Vault 

### ISSUE THREAD

**Issue by revit13** [mesh-for-data/mesh-for-data#337]
This is the first milestone of the solution chosen for grading remote modules with access to dataset credentials as described in  https://github.com/IBM/the-mesh-for-data/issues/140.

#### High level description of the solution:
- Single Vault instance with support for multiple kubernetes clusters.
- Modules would obtain secrets from Vault by:
-- Use Vault client to get the credentials via HTTPS request
-- Develop Vault plugin in go language to retrieve credentials (third party systems, K8S secretes) to get the dataset credentials. 

This milestone targets the ability of modules to send requests directly from Vault as described in  https://github.com/IBM/the-mesh-for-data/issues/140.

#### Out of scope for this milestone
- The implementation of a new plugin and thus the way dataset credentials are inserted to Vault will not change. 
- Using secure connection to retrieve the credentials.

The ability of the modules to support retrieval of  dataset credentials using secret-provider should remain unchanged in this milestone.

# Sub issues

- [ ] #335  Configure Vault to support K8S auth method in multi-cluster setup
- [X] #336 M4d-controller changes to support the ability of modules to send requests to Vault 
**Documentation :**
- [ ] #421 Add documentation in README .md file for Vault configuration (temporary documentation)
- [X] #435  Document the new Vault fields sent to the modules
