### ISSUE TITLE
Retrieve dataset credentials using Vault plugin

### ISSUE THREAD

**Issue by revit13** [mesh-for-data/mesh-for-data#406]
This is the second milestone of the solution to distributing credentials as described in #140.

This milestone focuses on using Vault secret plugins to retrieve datasets credentials directly from where they are stored: in a catalog or as kubernetes secrets, avoiding the need to copy them to the internal Vault as is done in the current implementation.

More information about the Vault plugin:
https://www.vaultproject.io/docs/internals/plugins

Sub-issues:

- [x] #414  Pluging setup: Add to vault helm installation different values.yaml files to load the plugin depending on the configuration.
- [x]  #448 Extend the catalog connector to return the secretPath in Vault which includes  vault plugin path and the details of the kubernetes secret to retrieve the credentials, if such secret exists. This information will be used by the modules when they send requests to Vault to retrieve the datasets credentials.
- [ ] (PR #592) Add documentation in project web-pages describing what is needs to be done to add a new plugin to the project.

**Comment by roee88** [comment]
Is removing the secret provider part of this milestone too?

**Comment by revit13** [comment]
Secret-provider removal is actually post milestone 1 phase (https://github.com/IBM/the-mesh-for-data/issues/337) as it could be removed after all modules will be able to send requests directly to Vault. (the removal is not part of milestone 1 though). I will add another issue once the modules will be ready if that makes sense. Anyway, I prefer to wait with the removal for a while even after such ability exists to validate everything works fine.

**Comment by revit13** [comment]
Rethinking about that, I'll move all the code removal (including in the connector) to last milestone.
